basic REST API
gastronauts/IT_APP_WED0730_SUSHI_BAR pull request #3
Opened 2018-03-11 19:41 UTC by MilBia

That's only basic server with few endpoint's. Full able to changes. Data types of variables in classes can by changed in next release.

2018-03-11 19:47 UTC, swojciechowski commented on .gitignore
> +.idea
Are you sure that we don' want to add idea projects? i mean, at some point this should be generic solution but for now we all depend on project configurations. IMO this should be removed.

2018-03-11 19:48 UTC, swojciechowski commented
I would suggest to split each model element to smaller patch. It is hard to review 800+ lines of code. Please, if not for review it is easier to fix on next pull request.

2018-03-22 17:24 UTC, MilBia commented
I remove .idea form .gitignore and split all code to init commit and others with basics of each module. In next tasks I will polish that endpoints and add changes if they needed that.

2018-03-24 11:09 UTC, pwr218154 requested changes
i will not approve for time being, let somebody also check it

2018-03-24 11:09 UTC, pwr218154 commented on .gitignore
> +vendor
No line ending/
is this custom ignore for your app? rather put this inside project folder (server)

2018-03-24 11:09 UTC, pwr218154 commented on server/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file is custom configuration (it is even added to .gitignore, you must have used add using wildcard or force option)
please do not commit this.

2018-03-24 11:09 UTC, swojciechowski commented on server/.idea/.name
> +mimosa-soft
maybe `sushi-server`?

2018-03-24 19:03 UTC, pwr218154 approved these changes

2018-03-24 19:04 UTC, merged